#include <windows.h>
#include <stdint.h>
#include <vector>
#include <array>
#include <cmath>     
#include <algorithm> 
#include <unordered_set>
#include <atlcoll.h>
#include <atlstr.h>
#include <atltypes.h>
#include <atlcom.h>
#include <atlfile.h>
#include <atlbase.h>
#include <d3d11.h>
#include <d3d9.h>
#include <wrl/client.h> 
#include <atlcomcli.h> 
#include "unordered_map"
#include "Misc/ComRoot.hpp"
#include "Common/MeshData.h"
#include "Common/GuidMap.h"
#include "Common/BoundingBox.h"
#include "Common/RenderingBuffers.h"
#include "Common/RenderState.h"

